### ISSUE TITLE
What is italc-mso?

### ISSUE THREAD

**Issue by d-m-wilson** [iTALC/italc-mso#1]
Please forgive me if an issue is not an appropriate way to ask this question: What is the difference between the [italc](https://github.com/iTALC/italc) and [italc-mso](https://github.com/iTALC/italc-mso) repositories?

**Comment by tobydox** [comment]
It's a development repository but has been merged into the iTALC successor Veyon - see https://github.com/veyon/veyon for details and watch out for the official announcements soon.
